//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_dae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int idCliente_pk { get; set; }
        public string nombreCliente { get; set; }
        public string DUI { get; set; }
        public string NIT { get; set; }
        public string NRC { get; set; }
    }
}
