//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_dae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int numeroFactura_pk { get; set; }
        public int idComprobante_fk { get; set; }
        public int idMetodoPago_fk { get; set; }
        public int idCliente_fk { get; set; }
        public int idCajero_fk { get; set; }
        public string fecha { get; set; }
    }
}
