//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_dae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int idProducto_pk { get; set; }
        public string descripcion { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<double> precioUnitario { get; set; }
    }
}
